import type { Metadata } from "next";
import "./globals.scss";

export const metadata: Metadata = {
  title: "My SaaS",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>{children}</body>
    </html>
  );
}
